# Generated by Django 5.2.1 on 2025-05-09 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parsedfile',
            old_name='content',
            new_name='extracted_text',
        ),
        migrations.RenameField(
            model_name='parsedfile',
            old_name='title',
            new_name='keyword',
        ),
        migrations.RemoveField(
            model_name='parsedfile',
            name='format',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='created_at',
        ),
        migrations.AddField(
            model_name='parsedfile',
            name='context_lines',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parsedfile',
            name='transcript',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scriptapi.transcript'),
            preserve_default=False,
        ),
    ]
