# Generated by Django 5.2.1 on 2025-05-09 05:35

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ("scriptapi", "0002_rename_content_parsedfile_extracted_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcript",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now
            ),
            preserve_default=False,
        )
    ]
