# Generated by Django 5.2.1 on 2025-05-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptapi', '0003_transcript_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('files', models.ManyToManyField(related_name='keywords', to='scriptapi.parsedfile')),
            ],
        ),
    ]
