# Generated by Django 5.2.1 on 2025-05-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptapi', '0004_keyword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='files',
        ),
        migrations.AddField(
            model_name='parsedfile',
            name='keywords',
            field=models.ManyToManyField(related_name='parsed_files', to='scriptapi.keyword'),
        ),
    ]
